services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/local
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: